stages:
  - triggers

terraform-review:
  stage: triggers
  trigger:
    include: .gitlab/ci/terraform/review.gitlab-ci.yml
    strategy: depend
  only:
    - branches
  except:
    - main

docker-review:
  stage: triggers
  trigger:
    include: .gitlab/ci/docker/review.gitlab-ci.yml
  only:
    - branches
  except:
    - main

terraform-production:
  stage: triggers
  trigger:
    include: .gitlab/ci/terraform/production.gitlab-ci.yml
    strategy: depend
  only:
    - main

docker-production:
  stage: triggers
  trigger:
    include: .gitlab/ci/docker/production.gitlab-ci.yml
  only:
    - main