stages:
  - bootstrap
  - terraform

terraform-bootstrap:
  stage: bootstrap
  trigger:
    include: .gitlab/ci/terraform/bootstrap.gitlab-ci.yml
    strategy: depend

terraform-review:
  stage: terraform
  trigger:
    include: .gitlab/ci/terraform/review.gitlab-ci.yml
    strategy: depend
  only:
    refs:
      - branches
  except:
    refs:
      - main
    variables:
      - $CI_COMMIT_MESSAGE =~ /docs:/

terraform-production:
  stage: terraform
  trigger:
    include: .gitlab/ci/terraform/production.gitlab-ci.yml
    strategy: depend
  only:
    refs:
      - main
