stages:
  - bootstrap
  - terraform

terraform-bootstrap:
  stage: bootstrap
  trigger:
    include: .gitlab/ci/terraform/bootstrap.gitlab-ci.yml
    strategy: depend
  allow_failure: true

terraform-review:
  stage: terraform
  trigger:
    include: .gitlab/ci/terraform/review.gitlab-ci.yml
    strategy: depend
  only:
    - branches
  except:
    - main

terraform-production:
  stage: terraform
  trigger:
    include: .gitlab/ci/terraform/production.gitlab-ci.yml
    strategy: depend
  only:
    - main
