stages:
  - deploy
  - release

terraform-review:
  stage: deploy
  trigger:
    include: .gitlab/ci/terraform/review.gitlab-ci.yml
    strategy: depend
  only:
    - branches
  except:
    - main

docker-review:
  stage: release
  trigger:
    include: .gitlab/ci/docker/review.gitlab-ci.yml
    strategy: depend
  only:
    - branches
  except:
    - main

terraform-production:
  stage: deploy
  trigger:
    include: .gitlab/ci/terraform/production.gitlab-ci.yml
    strategy: depend
  only:
    - main

docker-production:
  stage: release
  trigger:
    include: .gitlab/ci/docker/production.gitlab-ci.yml
    strategy: depend
  only:
    - main