version: "3"

services:
  citizen:
    container_name: citizen
    build:
      context: .
      dockerfile: ./apps/citizen/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - showcase

  tax-office:
    container_name: tax-office
    build:
      context: .
      dockerfile: ./apps/tax-office/Dockerfile
    restart: always
    ports:
      - "4000:3000"
    networks:
      - showcase

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  showcase:
    external: false