image: docker:20.10.16

stages:
  - build
  - release

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
  stage: build
  script:
    - docker compose build

release:
  stage: release
  script:
    - docker compose push
  only:
    - main
