image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/environments/production
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/production

before_script:
  - cd ${TF_ROOT}

stages:
  - prepare
  - validate
  - build
  - deploy
  - report

init:
  stage: prepare
  script:
    - gitlab-terraform init

validate:
  stage: validate
  script:
    - gitlab-terraform validate

plan:
  stage: build
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:
  stage: deploy
  script:
    - gitlab-terraform apply
    - echo "INSTANCE_CAR_INSURANCE_COMPANY_URL=$(gitlab-terraform output -raw instance_car-insurance-company_url)" >> build.env
    - echo "INSTANCE_CITIZEN_URL=$(gitlab-terraform output -raw instance_citizen_url)" >> build.env
    - echo "INSTANCE_CONSTRUCTION_OFFICE_URL=$(gitlab-terraform output -raw instance_construction-office_url)" >> build.env
    - echo "INSTANCE_CUSTOMS_URL=$(gitlab-terraform output -raw instance_customs_url)" >> build.env
    - echo "INSTANCE_EMPLOYMENT_AGENCY_URL=$(gitlab-terraform output -raw instance_employment-agency_url)" >> build.env
    - echo "INSTANCE_ENVIRONMENTAL_OFFICE_URL=$(gitlab-terraform output -raw instance_environmental-office_url)" >> build.env
    - echo "INSTANCE_LAND_REGISTRY_OFFICE_URL=$(gitlab-terraform output -raw instance_land-registry-office_url)" >> build.env
    - echo "INSTANCE_PARENTAL_BENEFITS_OFFICE_URL=$(gitlab-terraform output -raw instance_parental-benefits-office_url)" >> build.env
    - echo "INSTANCE_RECONSTRUCTION_LOAN_CORPORATION_URL=$(gitlab-terraform output -raw instance_reconstruction-loan-corporation_url)" >> build.env
    - echo "INSTANCE_REGISTRATION_OFFICE_URL=$(gitlab-terraform output -raw instance_registration-office_url)" >> build.env
    - echo "INSTANCE_TAX_OFFICE_URL=$(gitlab-terraform output -raw instance_tax-office_url)" >> build.env
    - echo "INSTANCE_TRADE_OFFICE_URL=$(gitlab-terraform output -raw instance_trade-office_url)" >> build.env
    - echo "INSTANCE_VEHICLE_REGISTRATION_OFFICE_URL=$(gitlab-terraform output -raw instance_vehicle-registration-office_url)" >> build.env
  artifacts:
    name: apply
    paths:
      - ${TF_ROOT}/build.env
    reports:
      dotenv: ${TF_ROOT}/build.env
  environment:
    name: production/apps
  dependencies:
    - plan

report_instance_car-insurance-company:
  stage: report
  script:
    - echo $INSTANCE_CAR_INSURANCE_COMPANY_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-car-insurance-company
    url: https://$INSTANCE_CAR_INSURANCE_COMPANY_URL
  dependencies:
    - apply

report_instance_citizen:
  stage: report
  script:
    - echo $INSTANCE_CITIZEN_URL
  environment:
    name: production/solid-showcase-citizen
    url: https://$INSTANCE_CITIZEN_URL
  needs:
    - apply

report_instance_construction-office:
  stage: report
  script:
    - echo $INSTANCE_CONSTRUCTION_OFFICE_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-construction-office
    url: https://$INSTANCE_CONSTRUCTION_OFFICE_URL
  dependencies:
    - apply

report_instance_customs:
  stage: report
  script:
    - echo $INSTANCE_CUSTOMS_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-customs
    url: https://$INSTANCE_CUSTOMS_URL
  dependencies:
    - apply

report_instance_employment-agency:
  stage: report
  script:
    - echo $INSTANCE_EMPLOYMENT_AGENCY_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-employment-agency
    url: https://$INSTANCE_EMPLOYMENT_AGENCY_URL
  dependencies:
    - apply

report_instance_environmental-office:
  stage: report
  script:
    - echo $INSTANCE_ENVIRONMENTAL_OFFICE_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-environmental-office
    url: https://$INSTANCE_ENVIRONMENTAL_OFFICE_URL
  dependencies:
    - apply

report_instance_land-registry-office:
  stage: report
  script:
    - echo $INSTANCE_LAND_REGISTRY_OFFICE_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-land-registry-office
    url: https://$INSTANCE_LAND_REGISTRY_OFFICE_URL
  dependencies:
    - apply

report_instance_parental-benefits-office:
  stage: report
  script:
    - echo $INSTANCE_PARENTAL_BENEFITS_OFFICE_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-parental-benefits-office
    url: https://$INSTANCE_PARENTAL_BENEFITS_OFFICE_URL
  dependencies:
    - apply

report_instance_reconstruction-loan-corporation:
  stage: report
  script:
    - echo $INSTANCE_RECONSTRUCTION_LOAN_CORPORATION_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-reconstruction-loan-corporation
    url: https://$INSTANCE_RECONSTRUCTION_LOAN_CORPORATION_URL
  dependencies:
    - apply

report_instance_registration-office:
  stage: report
  script:
    - echo $INSTANCE_REGISTRATION_OFFICE_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-registration-office
    url: https://$INSTANCE_REGISTRATION_OFFICE_URL
  dependencies:
    - apply

report_instance_tax-office:
  stage: report
  script:
    - echo $INSTANCE_TAX_OFFICE_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-tax-office
    url: https://$INSTANCE_TAX_OFFICE_URL
  dependencies:
    - apply

report_instance_trade-office:
  stage: report
  script:
    - echo $INSTANCE_TRADE_OFFICE_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-trade-office
    url: https://$INSTANCE_TRADE_OFFICE_URL
  dependencies:
    - apply

report_instance_vehicle-registration-office:
  stage: report
  script:
    - echo $INSTANCE_VEHICLE_REGISTRATION_OFFICE_URL
  environment:
    name: review-${CI_COMMIT_REF_NAME}/solid-showcase-vehicle-registration-office
    url: https://$INSTANCE_VEHICLE_REGISTRATION_OFFICE_URL
  dependencies:
    - apply