= RDF File Structure
:toc:
:icons: font

== Maindata

This is how the 'Maindata' resources work in our proposed structure:
Each Citizen has a Maindata container in their own Pod As of now these contain one resource: maindata.ttl

.Example: maindata.ttl
[,ttl]
----
include::maindata.ttl[]
----

The purpose of this resource is to be used with other service providers such as the Tax Office App.
It is not the same as the profile resource of the WebID

== Tax Data

Tax form data is saved in separate Pods for each citizen and can be accessed by that person, but not changed.

== Messages

To enable information flow between Government Apps, such as the Tax Office app and Citizens, each citizen Pod has an _inbox_ Container.
If there are new documents a message will be sent to the public inbox.

.Example: message.ttl
A message contains metadata using the http://schema.org/Message[Schema.org/message] type.
This contains information about sender, recipient and timestamp.

Additional information is given in rdf syntax

[,ttl]
----
include::message.ttl[]
----
